CompartiMoss.BootCamp/src/CompartiMoss.BootCamp.Web/Controllers/AutorController.cs
using CompartiMoss.BootCamp.Web.Services;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace CompartiMoss.BootCamp.Web.Controllers
{
    public class AutorController : Controller
    {
        private IAutor _service;

        public AutorController(IAutor service)
        {
            _service = service;
        }

        
        public IActionResult Index()
        {
            var autorCollection = _service.GetAllAutor();
            return View(autorCollection);
        }

        [HttpGet]
        public IActionResult Detail(string name)
        {
            var result = _service.GetAutorByName(name);
            return View(result);
        }

     
    }
}

CompartiMoss.BootCamp/src/CompartiMoss.BootCamp.Web/Controllers/RevistaController.cs
using CompartiMoss.BootCamp.Web.Services;
using Microsoft.AspNet.Mvc;

namespace DotNet.CompartiMOSS.Controllers
{
    public class RevistaController : Controller
    {
        private IRevista _service;
        public RevistaController(IRevista service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            var revistaCollection = _service.GetRevistas();
            return View(revistaCollection);
        }

        public IActionResult Detail(string name)
        {
            var revista = _service.GetRevistaByTitle(name);
            return View(revista);
        }
    }
}

CompartiMoss.BootCamp/src/CompartiMoss.BootCamp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Azure BootCamp.CompartiMOSS</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
            <link rel="stylesheet" href="~/css/compartimoss.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <div id="divMain">
            <header id="divHeader">
                <div id="divLogo">
                </div>
                <div id="divHeaderContent">
                    <div id="divSearch">
                    </div>
                    <nav id="MainMenu">
                        <div data-name="TopNavigationNoFlyoutWithStartNode">


                            <div id="DeltaTopNavigation" class="ms-displayInline ms-core-navigation ms-dialogHidden">




                                <div id="zz1_TopNavigationMenu" class=" noindex ms-core-listMenu-horizontalBox">
                                    <ul id="zz2_RootAspMenu" class="root ms-core-listMenu-root static">
                                        <li class="static home" >
                                            <a asp-controller="Home" asp-action="Index" class="static menu-item ms-core-listMenu-item ms-displayInline ms-navedit-linkNode home" tabindex="0" [routerLink]="['Inicio']" accesskey="1">
                                                <span class="additional-background ms-navedit-flyoutArrow">
                                                    <span class="menu-item-text"> Inicio</span>
                                                </span>
                                            </a>
                                        </li>
                                        <li class="static revista">
                                            <a asp-controller="Revista" asp-action="Index" class="static menu-item ms-core-listMenu-item ms-displayInline ms-navedit-linkNode revista" tabindex="0" [routerLink]="['Revista']">
                                                <span class="additional-background ms-navedit-flyoutArrow">
                                                    <span class="menu-item-text">Revistas</span>
                                                </span>
                                            </a>
                                        </li>
                                        <li class="static autor">
                                            <a asp-controller="Autor" asp-action="Index" class="static menu-item ms-core-listMenu-item ms-displayInline ms-navedit-linkNode autor" tabindex="0" [routerLink]="['Autor']">
                                                <span class="additional-background ms-navedit-flyoutArrow">
                                                    <span class="menu-item-text">Autores</span>
                                                </span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>



                        </div>
                    </nav>
                </div>
            </header>

            
                @RenderBody()            
                <footer id="divFooter">
                    <div id="FooterAds">
                        <a href="http://www.microsoftvirtualacademy.com/" target="_blank">
                            <img src="http://compartimoss.com/PublishingImages/Partners/banner_mva.png" alt="Microsoft Virtual Academy" title="Microsoft Virtual Academy">
                        </a>
                    </div>
                    <div id="FooterSocial">
                        <a href="http://www.linkedin.com/groups?gid=3776291&amp;trk=hb_side_g" target="linkedin">
                            <img src="http://compartimoss.com/_catalogs/masterpage/CompartiMOSS/Images/Layout/Linkedin.png" alt="Siguemos en LinkedIn" title="Siguemos en LinkedIn">
                        </a>
                        <a href="http://twitter.com/CompartiMOSScom" target="twitter">
                            <img src="http://compartimoss.com/_catalogs/masterpage/CompartiMOSS/Images/Layout/Twitter.png" alt="Siguemos en Twitter" title="Siguemos en Twitter">
                        </a>
                        <a href="http://www.compartimoss.com/Apps" target="_blank">
                            <img src="http://compartimoss.com/_catalogs/masterpage/CompartiMOSS/Images/AppDownload.png" alt="Descarga nuestras apps" title="Descarga nuestras apps">
                        </a>
                    </div>
                    <div id="FooterPowered">
                        <img id="imgSPPowered" src="http://compartimoss.com/_catalogs/masterpage/CompartiMOSS/Images/Layout/Powered-By-SharePoint.png" alt="Powered by SharePoint" title="Powered by SharePoint">
                        | Powered by <span id="spanGSCPowered"><a href="http://www.encamina.com">ENCAMINA </a></span>
                    </div>
                </footer>            
        </div>
        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>